minio:
  enabled: true
  mode: standalone
  rootUser: grafana-tempo
  rootPassword: supersecret
  buckets:
    # Default Tempo storage bucket
    - name: tempo-traces
      policy: none
      purge: false
  persistence:
    size: 10Gi
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi

traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  zipkin:
    enabled: false
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false

# metricsGenerator 로 service-graphs 설정 하지 않으면 tempo 에서 service-graphs 가 보여지지 않는다.
# grafana agent 의 설정은 동작하지 않았다.
metricsGenerator:
  enabled: true
  config:
    storage:
      remote_write:
        - url: http://mimir-nginx.mimir.svc.cluster.local:80/api/v1/push
          send_exemplars: false

global_overrides:
  metrics_generator_processors:
    - service-graphs
